# Generated by Django 5.2.4 on 2025-08-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/audio/', verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/videos/', verbose_name='Видео'),
        ),
    ]
