# Generated by Django 5.2.5 on 2025-08-20 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон рассылки',
                'verbose_name_plural': 'Шаблоны рассылок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('send_to_all', models.BooleanField(default=False, verbose_name='Отправить всем пользователям')),
                ('send_to_active', models.BooleanField(default=False, verbose_name='Отправить только активным пользователям')),
                ('send_to_new', models.BooleanField(default=False, verbose_name='Отправить только новым пользователям (зарегистрированным за последние 7 дней)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланированная дата отправки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Общее количество получателей')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Количество отправленных')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Количество неудачных отправок')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_newsletters', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Новостная рассылка',
                'verbose_name_plural': 'Новостные рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки'), ('bounced', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='newsletters.newsletter', verbose_name='Рассылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_recipients', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылок',
                'unique_together': {('newsletter', 'user')},
            },
        ),
    ]
